AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - .bundle/**/*
    - bundle_bin/**/*
Metrics/AbcSize:
  Exclude:
    - lib/**/*
Metrics/MethodLength:
  Exclude:
    - lib/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
