AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - .bundle/**/*
    - bundle_bin/**/*
Metrics/AbcSize:
  Exclude:
    - lib/**/*
Metrics/MethodLength:
  Exclude:
    - lib/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
